// ===== Schildersammlung: Kategorien und Erklärungen je Zeichennummer =====
// Schlüssel = Grundnummer des Zeichens (z. B. "274" gilt für 274-10 bis 274-130).
// t = Name, e = Erklärung. Die Bilder selbst stehen in schilder-daten.js.

export const KATEGORIEN = [
  { id: "gefahr", name: "Gefahrzeichen", kurz: "GEFAHR",
    e: "Gefahrzeichen warnen vor einer Gefahrstelle. Außerorts stehen sie meist 150 bis 250 m davor, innerorts kurz davor. Steht die Gefahrstelle woanders, zeigt das ein Zusatzzeichen. Pass deine Geschwindigkeit an und sei bremsbereit." },
  { id: "vorschrift", name: "Vorschriftzeichen", kurz: "VORSCHRIFT",
    e: "Vorschriftzeichen sind Gebote und Verbote – auch die Markierungen auf der Fahrbahn gehören dazu. Du musst sie befolgen, sonst drohen Bußgeld und Punkte. Sie gelten ab dem Standort des Zeichens." },
  { id: "richt", name: "Richtzeichen", kurz: "RICHT",
    e: "Richtzeichen geben dir Hinweise, die den Verkehr erleichtern. Manche enthalten aber auch Regeln, z. B. die Vorfahrtstraße, die Ortstafel oder die Autobahn." },
  { id: "weg", name: "Wegweiser & Umleitung", kurz: "WEGWEISER",
    e: "Wegweiser zeigen Ziele, Entfernungen und Straßennummern. Gelb sind sie auf Bundesstraßen, blau auf Autobahnen und weiß auf sonstigen Straßen. Umleitungen sind gelb mit schwarzer Schrift, Bedarfsumleitungen an Autobahnen blau." },
  { id: "lenk", name: "Verkehrslenkungstafeln", kurz: "LENKUNG",
    e: "Verkehrslenkungstafeln stehen vor allem vor Baustellen. Sie zeigen dir, wie die Fahrstreifen weiter verlaufen. Eingezeichnete Verkehrszeichen gelten nur für den Fahrstreifen, auf dem sie abgebildet sind." },
  { id: "einr", name: "Verkehrseinrichtungen", kurz: "EINRICHTUNG",
    e: "Schranken, Baken, Leitkegel, Leitpfosten und ähnliche Einrichtungen. Sie gehen den allgemeinen Verkehrsregeln vor. Was sie absperren, darfst du nicht befahren." },
  { id: "zusatz", name: "Zusatzzeichen", kurz: "ZUSATZ",
    e: "Zusatzzeichen stehen unter einem Verkehrszeichen und gelten nur für dieses Zeichen. Sie schränken es ein (z. B. Uhrzeiten, „nur Lkw“) oder machen Ausnahmen („Anlieger frei“) oder geben zusätzliche Hinweise (z. B. Entfernungen)." },
  { id: "sonst", name: "Sonstige Zeichen", kurz: "SONSTIGE",
    e: "Grünpfeile, Lichtzeichen an Bahnübergängen und nichtamtliche Hinweisschilder." }
];

export function kategorie(nr) {
  const n = parseFloat(nr);
  if (!isFinite(n)) return "sonst";
  if (n < 200) return "gefahr";
  if (n < 300) return "vorschrift";
  if (n < 400) return "richt";
  if (n < 500) return "weg";
  if (n < 600) return "lenk";
  if (n < 700) return "einr";
  if (n >= 1000) return "zusatz";
  return "sonst";
}

export const INFO = {
  // ---------- Gefahrzeichen ----------
  "101": { t: "Gefahrstelle", e: "Allgemeines Warnzeichen. Ein Sinnbild im Zeichen oder ein Zusatzzeichen nennt die Gefahr, z. B. Flugbetrieb, Steinschlag, Schnee- oder Eisglätte, Ufer oder eine bewegliche Brücke. Fahr vorsichtig und bremsbereit." },
  "102": { t: "Kreuzung oder Einmündung mit Vorfahrt von rechts", e: "An der nächsten Kreuzung oder Einmündung gilt „rechts vor links“. Fahr langsam heran und lass Fahrzeuge von rechts zuerst fahren." },
  "103": { t: "Kurve", e: "Gefährliche Kurve in Pfeilrichtung. Brems vor der Kurve ab, nicht in der Kurve." },
  "105": { t: "Doppelkurve", e: "Zwei gefährliche Kurven hintereinander, die erste in Pfeilrichtung. Überholen ist hier meist zu gefährlich." },
  "108": { t: "Gefälle", e: "Starkes Gefälle. Die Zahl nennt die Neigung: 10 % heißt 10 m Höhenunterschied auf 100 m. Schalte rechtzeitig zurück und nutze die Motorbremse, damit die Bremsen nicht überhitzen." },
  "110": { t: "Steigung", e: "Starke Steigung mit der angegebenen Neigung in Prozent. Schalte rechtzeitig zurück. Rechne mit langsamen Lkw und Gespannen." },
  "112": { t: "Unebene Fahrbahn", e: "Schlaglöcher, Bodenwellen oder Frostaufbrüche. Fahr langsamer, damit du das Fahrzeug sicher im Griff behältst." },
  "114": { t: "Schleuder- oder Rutschgefahr", e: "Bei Nässe oder Schmutz besteht erhöhte Schleudergefahr. Ein Zusatzzeichen kann den Grund nennen. Langsam fahren, sanft lenken und vorsichtig bremsen." },
  "117": { t: "Seitenwind", e: "Starker Seitenwind von der gezeigten Seite, z. B. auf Brücken oder an Waldschneisen. Halt das Lenkrad gut fest – besonders mit Anhänger, Dachbox oder hohem Fahrzeug." },
  "120": { t: "Verengte Fahrbahn", e: "Die Fahrbahn wird beidseitig schmaler. Achte auf Gegenverkehr und lass ihn notfalls vorbei." },
  "121": { t: "Einseitig verengte Fahrbahn", e: "Die Fahrbahn wird auf der gezeigten Seite schmaler. Ordne dich rechtzeitig ein und achte auf den Verkehr neben dir." },
  "123": { t: "Arbeitsstelle", e: "Baustelle voraus. Rechne mit Arbeitern, Baufahrzeugen, Schmutz und engen Fahrstreifen und fahr entsprechend langsam." },
  "124": { t: "Stau", e: "Hier staut sich der Verkehr häufig. Werde langsamer, halte mehr Abstand und rechne mit stehenden Fahrzeugen. Auf der Autobahn darfst du am Stauende das Warnblinklicht einschalten." },
  "125": { t: "Gegenverkehr", e: "Auf deiner Fahrbahn kommt dir jetzt Verkehr entgegen, z. B. bei einer Baustelle auf der Autobahn. Halte dich rechts und überhole nicht." },
  "131": { t: "Lichtzeichenanlage", e: "Eine Ampel folgt, die man oft spät sieht. Sei bremsbereit." },
  "133": { t: "Fußgänger", e: "Fußgänger überqueren hier häufig die Fahrbahn oder gehen auf ihr. Das ist kein Zebrastreifen, verlangt aber besondere Vorsicht." },
  "136": { t: "Kinder", e: "Hier sind oft Kinder unterwegs, z. B. an Schulen oder Spielplätzen. Fahr langsam und bremsbereit – Kinder laufen oft plötzlich los." },
  "138": { t: "Radverkehr", e: "Radfahrende kreuzen oder fahren auf die Fahrbahn. Beim Überholen gilt innerorts mindestens 1,5 m und außerorts mindestens 2 m Seitenabstand." },
  "142": { t: "Wildwechsel", e: "Mit Wild auf der Fahrbahn rechnen, besonders in der Dämmerung. Taucht ein Tier auf: abblenden, hupen, bremsen und das Lenkrad gerade halten. Weich nicht riskant aus." },
  "145": { t: "Kraftomnibusse", e: "Warnt vor Omnibussen, z. B. an Busein- und -ausfahrten. Rechne mit Bussen, die einbiegen oder die Fahrbahn kreuzen." },
  "150": { t: "Beschrankter Bahnübergang", e: "Ältere Ausführung: Bahnübergang mit Schranken oder Halbschranken. Heute wird dafür Zeichen 151 verwendet. Schienenfahrzeuge haben immer Vorrang." },
  "151": { t: "Bahnübergang", e: "Bahnübergang voraus. Fahr mit mäßiger Geschwindigkeit heran. Ab dem Zeichen bis hinter die Gleise darfst du keine Kraftfahrzeuge überholen. Schienenfahrzeuge haben immer Vorrang." },
  "153": { t: "Dreistreifige Bake vor beschranktem Bahnübergang", e: "Ältere Ausführung der Bake etwa 240 m vor einem Bahnübergang. Heute: Zeichen 156 bzw. 157." },
  "156": { t: "Bahnübergang mit dreistreifiger Bake", e: "Steht etwa 240 m vor einem Bahnübergang. Danach folgen die zweistreifige (ca. 160 m) und die einstreifige Bake (ca. 80 m). Ab hier darfst du keine Kraftfahrzeuge mehr überholen." },
  "157": { t: "Dreistreifige Bake", e: "Etwa 240 m bis zum Bahnübergang. Die Streifen zählen herunter: 3 – 2 – 1." },
  "159": { t: "Zweistreifige Bake", e: "Etwa 160 m bis zum Bahnübergang." },
  "162": { t: "Einstreifige Bake", e: "Etwa 80 m bis zum Bahnübergang." },

  // ---------- Vorschriftzeichen ----------
  "201": { t: "Andreaskreuz", e: "Dem Schienenverkehr Vorrang gewähren! Vor und hinter dem Andreaskreuz ist das Parken verboten: innerorts bis je 5 m, außerorts bis je 50 m. Der Blitzpfeil zeigt eine Oberleitung mit Hochspannung." },
  "205": { t: "Vorfahrt gewähren!", e: "Du musst Vorfahrt gewähren. Fahr nur so schnell heran, dass du notfalls rechtzeitig anhalten kannst. Anhalten musst du nur, wenn jemand Vorfahrt hat." },
  "206": { t: "Halt! Vorfahrt gewähren!", e: "Stoppschild: Du musst anhalten – auch wenn frei ist. An der Haltlinie, ohne Haltlinie dort, wo du die Straße einsehen kannst. Erst wenn die Räder stillstehen, ist es ein Halt. Danach Vorfahrt gewähren." },
  "208": { t: "Dem Gegenverkehr Vorrang gewähren!", e: "An der folgenden Engstelle hat der Gegenverkehr Vorrang. Warte, bis er durchgefahren ist." },
  "209": { t: "Vorgeschriebene Fahrtrichtung", e: "An der nächsten Kreuzung oder Einmündung musst du in Pfeilrichtung fahren." },
  "211": { t: "Vorgeschriebene Fahrtrichtung – hier", e: "Du musst direkt hinter dem Zeichen in Pfeilrichtung abbiegen." },
  "214": { t: "Vorgeschriebene Fahrtrichtungen", e: "Nur die gezeigten Richtungen sind erlaubt, z. B. geradeaus oder rechts." },
  "215": { t: "Kreisverkehr", e: "Im Kreisverkehr fährst du rechts herum. Steht darunter „Vorfahrt gewähren!“, hat der Verkehr im Kreis Vorfahrt. Beim Einfahren nicht blinken, beim Ausfahren blinken. Halten auf der Kreisfahrbahn ist verboten; die Mittelinsel darf nur überfahren werden, wenn dein Fahrzeug sonst nicht durchkommt." },
  "220": { t: "Einbahnstraße", e: "Fahren nur in Pfeilrichtung. Mit Zusatzzeichen kann Radverkehr in Gegenrichtung erlaubt sein – rechne damit. In Einbahnstraßen darfst du auch links halten und parken." },
  "222": { t: "Vorgeschriebene Vorbeifahrt", e: "Du musst an dem Hindernis oder der Verkehrsinsel auf der gezeigten Seite vorbeifahren." },
  "223.1": { t: "Seitenstreifen befahren", e: "Der Seitenstreifen ist freigegeben und wird wie ein Fahrstreifen benutzt – meist auf Autobahnen bei viel Verkehr." },
  "223.2": { t: "Seitenstreifen nicht mehr befahren", e: "Die Freigabe des Seitenstreifens endet. Wechsle rechtzeitig auf die normalen Fahrstreifen." },
  "223.3": { t: "Seitenstreifen räumen", e: "Der Seitenstreifen endet gleich. Wechsle jetzt nach links auf die Fahrstreifen." },
  "224": { t: "Haltestelle", e: "Haltestelle für Linienbusse oder Straßenbahnen. Bis 15 m vor und hinter dem Schild darfst du nicht parken. Fährt ein Bus mit Warnblinklicht an die Haltestelle heran, darfst du ihn nicht überholen. Steht er mit Warnblinklicht, darfst du nur mit Schrittgeschwindigkeit vorbeifahren – auch im Gegenverkehr." },
  "229": { t: "Taxenstand", e: "Hier dürfen nur Taxen halten, die auf Fahrgäste warten. Für alle anderen ist das Halten verboten." },
  "230": { t: "Ladebereich", e: "Kennzeichnet einen Bereich zum Be- und Entladen, z. B. für den Lieferverkehr. Zum Parken ist er nicht gedacht; Zusatzzeichen können Zeiten oder Fahrzeugarten festlegen. Das Zeichen ist 2024 neu in die StVO gekommen." },
  "237": { t: "Radweg", e: "Radfahrende müssen diesen Radweg benutzen. Andere Fahrzeuge dürfen ihn nicht benutzen. Auch E-Scooter müssen hier fahren." },
  "238": { t: "Reitweg", e: "Reiter müssen diesen Weg benutzen, andere Verkehrsteilnehmer dürfen ihn nicht benutzen." },
  "239": { t: "Gehweg", e: "Nur für Fußgänger. Andere dürfen ihn nur mit Zusatzzeichen benutzen (z. B. „Radfahrer frei“) – und dann nur mit Schrittgeschwindigkeit." },
  "240": { t: "Gemeinsamer Geh- und Radweg", e: "Radfahrende müssen diesen Weg benutzen und dabei Rücksicht auf Fußgänger nehmen. Wenn nötig, langsamer fahren." },
  "241": { t: "Getrennter Rad- und Gehweg", e: "Der Weg ist geteilt: Radfahrende benutzen ihre Seite, Fußgänger ihre." },
  "242.1": { t: "Beginn einer Fußgängerzone", e: "Fahrzeuge sind verboten. Ist mit Zusatzzeichen etwas erlaubt (z. B. Lieferverkehr), dann nur mit Schrittgeschwindigkeit und ohne Fußgänger zu behindern." },
  "242.2": { t: "Ende einer Fußgängerzone", e: "Die Fußgängerzone endet." },
  "244.1": { t: "Beginn einer Fahrradstraße", e: "Andere Fahrzeuge nur mit Zusatzzeichen. Für alle gilt höchstens 30 km/h. Radfahrende dürfen nebeneinander fahren und dürfen nicht behindert werden." },
  "244.2": { t: "Ende einer Fahrradstraße", e: "Die Fahrradstraße endet; es gelten wieder die normalen Regeln." },
  "244.3": { t: "Beginn einer Fahrradzone", e: "Wie bei der Fahrradstraße, aber für eine ganze Zone: höchstens 30 km/h, Radfahrende dürfen nebeneinander fahren, andere Fahrzeuge nur mit Zusatzzeichen." },
  "244.4": { t: "Ende einer Fahrradzone", e: "Die Fahrradzone endet." },
  "245": { t: "Bussonderfahrstreifen", e: "Nur für Linienbusse. Mit Zusatzzeichen auch z. B. für Taxis oder Radfahrende. Alle anderen dürfen ihn nicht befahren." },
  "250": { t: "Verbot für Fahrzeuge aller Art", e: "Fahren ist für alle Fahrzeuge verboten. Fahrräder und Motorräder darfst du schieben." },
  "251": { t: "Verbot für Kraftwagen", e: "Verbot für Kraftwagen und andere mehrspurige Kraftfahrzeuge, also z. B. Pkw, Lkw und Busse. Motorräder dürfen fahren." },
  "253": { t: "Verbot für Kraftfahrzeuge über 3,5 t", e: "Verbot für Kraftfahrzeuge über 3,5 t zulässiger Gesamtmasse, auch mit Anhänger, und für Zugmaschinen. Pkw und Busse sind ausgenommen." },
  "254": { t: "Verbot für Radverkehr", e: "Radfahren ist hier verboten." },
  "255": { t: "Verbot für Krafträder", e: "Verbot für Motorräder (auch mit Beiwagen), Kleinkrafträder und Mofas." },
  "257": { t: "Verbot für bestimmte Verkehrsarten", e: "Verbot für die abgebildete Verkehrsart, z. B. Mofas, Reiter, Gespannfuhrwerke oder Pkw mit Anhänger. Mehrere Sinnbilder können auf einem Schild kombiniert sein." },
  "259": { t: "Verbot für Fußgänger", e: "Fußgänger dürfen hier nicht gehen." },
  "260": { t: "Verbot für Kraftfahrzeuge", e: "Verbot für alle Kraftfahrzeuge – vom Mofa bis zum Lkw." },
  "261": { t: "Verbot für Fahrzeuge mit gefährlichen Gütern", e: "Verbot für Fahrzeuge, die gefährliche Güter transportieren und deshalb orange Warntafeln führen müssen." },
  "262": { t: "Verbot über tatsächliche Masse", e: "Verbot für Fahrzeuge, deren tatsächliches Gewicht (mit Ladung) über der angegebenen Zahl liegt, z. B. vor Brücken. Achtung: Hier zählt das echte Gewicht, nicht die zulässige Gesamtmasse." },
  "263": { t: "Verbot über tatsächliche Achslast", e: "Verbot für Fahrzeuge, deren tatsächliche Achslast über dem angegebenen Wert liegt." },
  "264": { t: "Verbot über tatsächliche Breite", e: "Verbot für Fahrzeuge, die – einschließlich Ladung – breiter sind als angegeben. Denk an deine Spiegel und an Anhänger." },
  "265": { t: "Verbot über tatsächliche Höhe", e: "Verbot für Fahrzeuge, die – einschließlich Ladung – höher sind als angegeben, z. B. vor Brücken oder Unterführungen. Denk an Dachbox oder Fahrräder auf dem Dach." },
  "266": { t: "Verbot über tatsächliche Länge", e: "Verbot für Fahrzeuge und Züge, die – einschließlich Ladung – länger sind als angegeben. Mit Anhänger zählt die Gesamtlänge." },
  "267": { t: "Verbot der Einfahrt", e: "Einfahren verboten – typisch am Ende einer Einbahnstraße. Mit Zusatzzeichen kann Radverkehr erlaubt sein." },
  "268": { t: "Schneeketten sind vorgeschrieben", e: "Ab hier musst du Schneeketten aufgezogen haben. Damit darfst du höchstens 50 km/h fahren." },
  "269": { t: "Verbot für Fahrzeuge mit wassergefährdender Ladung", e: "Verbot für Fahrzeuge mit wassergefährdender Ladung, z. B. Heizöl oder Chemikalien – meist in Wasserschutzgebieten." },
  "270.1": { t: "Beginn einer Umweltzone", e: "Einfahren dürfen nur Fahrzeuge mit der passenden Umweltplakette. Welche Plakette erlaubt ist, steht auf dem Zusatzzeichen." },
  "270.2": { t: "Ende einer Umweltzone", e: "Die Umweltzone endet." },
  "272": { t: "Verbot des Wendens", e: "Wenden ist hier verboten." },
  "273": { t: "Verbot des Unterschreitens des Mindestabstands", e: "Kraftfahrzeuge über 3,5 t zulässiger Gesamtmasse und Busse dürfen den angegebenen Abstand zum Vordermann nicht unterschreiten." },
  "274": { t: "Zulässige Höchstgeschwindigkeit", e: "Du darfst nicht schneller fahren als angegeben. Das gilt ab dem Schild, bis es durch ein Ende-Zeichen (278 oder 282) aufgehoben wird. Ohne Schild gelten für Pkw innerorts 50 km/h und außerorts 100 km/h." },
  "274.1": { t: "Beginn einer Tempo-30-Zone", e: "In der ganzen Zone gilt höchstens 30 km/h (bzw. 20 km/h in verkehrsberuhigten Geschäftsbereichen). In Tempo-30-Zonen gilt meist „rechts vor links“." },
  "274.2": { t: "Ende einer Tempo-30-Zone", e: "Die Zone endet. Danach gilt wieder die normale Höchstgeschwindigkeit – innerorts also 50 km/h, wenn nichts anderes angegeben ist." },
  "275": { t: "Vorgeschriebene Mindestgeschwindigkeit", e: "Du darfst nicht langsamer fahren als angegeben – außer Verkehr, Sicht oder Wetter erfordern es. Fahrzeuge, die so schnell nicht fahren können, dürfen die Strecke nicht benutzen." },
  "276": { t: "Überholverbot", e: "Kraftfahrzeuge dürfen keine mehrspurigen Kraftfahrzeuge und keine Motorräder mit Beiwagen überholen. Einspurige Fahrzeuge wie Fahrräder und Motorräder darfst du überholen." },
  "277": { t: "Überholverbot für Kraftfahrzeuge über 3,5 t", e: "Kraftfahrzeuge über 3,5 t zulässiger Gesamtmasse (auch mit Anhänger) und Zugmaschinen dürfen keine mehrspurigen Kraftfahrzeuge überholen. Pkw und Busse sind ausgenommen. (Ältere Ausführungen nannten noch 2,8 t.)" },
  "277.1": { t: "Überholverbot für einspurige Fahrzeuge", e: "Mehrspurige Kraftfahrzeuge dürfen hier keine einspurigen Fahrzeuge überholen, also z. B. keine Radfahrenden und Motorräder. Gibt es seit 2020." },
  "278": { t: "Ende der zulässigen Höchstgeschwindigkeit", e: "Das Tempolimit endet. Danach gilt wieder die allgemeine Höchstgeschwindigkeit, z. B. 100 km/h außerorts." },
  "279": { t: "Ende der Mindestgeschwindigkeit", e: "Die vorgeschriebene Mindestgeschwindigkeit endet." },
  "280": { t: "Ende des Überholverbots", e: "Das Überholverbot für Kraftfahrzeuge aller Art endet." },
  "281": { t: "Ende des Überholverbots für Kraftfahrzeuge über 3,5 t", e: "Das Überholverbot für schwere Kraftfahrzeuge endet." },
  "281.1": { t: "Ende des Überholverbots für einspurige Fahrzeuge", e: "Einspurige Fahrzeuge dürfen wieder überholt werden – mit genug Seitenabstand." },
  "282": { t: "Ende sämtlicher Streckenverbote", e: "Alle vorher angeordneten Streckenverbote enden, z. B. Tempolimits und Überholverbote." },
  "283": { t: "Absolutes Haltverbot", e: "Halten auf der Fahrbahn ist verboten – auch nur kurz. Es gilt ab dem Schild bis zur nächsten Kreuzung oder bis zum Ende-Pfeil und nur auf der Straßenseite, auf der das Schild steht." },
  "286": { t: "Eingeschränktes Haltverbot", e: "Halten ist höchstens 3 Minuten erlaubt. Ein- und Aussteigen sowie Be- und Entladen darf auch länger dauern, muss aber zügig gehen. Parken ist verboten." },
  "290.1": { t: "Beginn eines eingeschränkten Haltverbots für eine Zone", e: "In der ganzen Zone gilt das eingeschränkte Haltverbot: höchstens 3 Minuten halten, außer zum Ein- und Aussteigen oder Be- und Entladen. Parken nur auf gekennzeichneten Flächen." },
  "290.2": { t: "Ende eines eingeschränkten Haltverbots für eine Zone", e: "Die Haltverbotszone endet." },
  "293": { t: "Fußgängerüberweg (Zebrastreifen)", e: "Fußgängern, die erkennbar über die Straße wollen, musst du das Überqueren ermöglichen. Fahr mit mäßiger Geschwindigkeit heran. Überholen ist hier verboten, Halten auf und bis 5 m vor dem Zebrastreifen ebenfalls." },
  "294": { t: "Haltlinie", e: "Hier musst du anhalten, wenn ein Stoppschild, eine rote Ampel oder ein Polizist es anordnet." },
  "295": { t: "Fahrstreifenbegrenzung / Fahrbahnbegrenzung", e: "Durchgezogene Linie: nicht überfahren und nicht darauf fahren. Halten ist verboten, wenn zwischen deinem Fahrzeug und der Linie weniger als 3 m Platz bleiben." },
  "296": { t: "Einseitige Fahrstreifenbegrenzung", e: "Du darfst die Linie nur von der Seite der unterbrochenen Linie aus überfahren, z. B. zum Überholen." },
  "297": { t: "Richtungspfeile", e: "Sind zwischen den Pfeilen Linien markiert, musst du an der nächsten Kreuzung in Pfeilrichtung fahren. Wähle deinen Fahrstreifen also rechtzeitig. Auf der Strecke mit Pfeilen darfst du nicht halten." },
  "297.1": { t: "Vorankündigungspfeil", e: "Kündigt an, dass der Fahrstreifen endet oder eine durchgezogene Linie beginnt. Wechsle rechtzeitig den Fahrstreifen bzw. beende den Überholvorgang." },
  "298": { t: "Sperrfläche", e: "Schraffierte Fläche: nicht befahren, nicht darauf halten und nicht parken." },
  "299": { t: "Grenzmarkierung für Halt- und Parkverbote", e: "Zickzacklinie: Sie verlängert oder verkürzt ein Halt- oder Parkverbot, z. B. vor Einfahrten oder Haltestellen. Hier darfst du nicht halten bzw. parken." },

  // ---------- Richtzeichen ----------
  "301": { t: "Vorfahrt", e: "Du hast Vorfahrt an der nächsten Kreuzung oder Einmündung – nur dort." },
  "306": { t: "Vorfahrtstraße", e: "Du hast Vorfahrt an allen folgenden Kreuzungen und Einmündungen, bis die Vorfahrtstraße endet. Außerorts ist das Parken auf der Fahrbahn verboten. Ein Zusatzzeichen kann eine abknickende Vorfahrt zeigen." },
  "307": { t: "Ende der Vorfahrtstraße", e: "Die Vorfahrtstraße endet. An der nächsten Kreuzung gilt wieder die Beschilderung dort – sonst „rechts vor links“." },
  "308": { t: "Vorrang vor dem Gegenverkehr", e: "An der folgenden Engstelle hast du Vorrang. Fahr trotzdem vorsichtig – der Gegenverkehr könnte das Schild übersehen." },
  "310": { t: "Ortstafel (Vorderseite)", e: "Hier beginnt die geschlossene Ortschaft. Ab der Tafel gilt höchstens 50 km/h, wenn nichts anderes angegeben ist." },
  "311": { t: "Ortstafel (Rückseite)", e: "Hier endet die geschlossene Ortschaft. Es gelten wieder die Regeln für außerorts, z. B. 100 km/h für Pkw." },
  "314": { t: "Parken", e: "Parken ist hier erlaubt. Zusatzzeichen können es beschränken, z. B. auf eine Parkdauer, mit Parkschein oder nur für bestimmte Fahrzeuge." },
  "314.1": { t: "Beginn einer Parkraumbewirtschaftungszone", e: "In der ganzen Zone darfst du nur mit Parkschein oder Parkscheibe parken – wie auf dem Zeichen angegeben." },
  "314.2": { t: "Ende einer Parkraumbewirtschaftungszone", e: "Die Parkzone endet." },
  "315": { t: "Parken auf Gehwegen", e: "Parken auf dem Gehweg ist erlaubt – aber nur so, wie es das Sinnbild zeigt (ganz oder halb, längs oder quer) und nur für Fahrzeuge bis 2,8 t zulässiger Gesamtmasse." },
  "316": { t: "Parken und Reisen / Mitfahren", e: "Park-and-Ride-Parkplatz: Hier parkst du und fährst mit Bus, Bahn oder in einer Fahrgemeinschaft weiter." },
  "317": { t: "Wandererparkplatz", e: "Parkplatz für Wanderer." },
  "318": { t: "Parkscheibe", e: "Parken nur mit Parkscheibe und für die angegebene Höchstdauer. Stell die Ankunftszeit auf die nächste halbe Stunde ein." },
  "325.1": { t: "Beginn eines verkehrsberuhigten Bereichs", e: "Spielstraße: Hier gilt Schrittgeschwindigkeit. Fußgänger dürfen die ganze Straße benutzen, Kinder dürfen überall spielen. Parken nur auf markierten Flächen. Beim Herausfahren musst du allen anderen Vorrang lassen." },
  "325.2": { t: "Ende eines verkehrsberuhigten Bereichs", e: "Der verkehrsberuhigte Bereich endet. Beim Herausfahren musst du den fließenden Verkehr durchlassen." },
  "327": { t: "Tunnel", e: "Im Tunnel musst du Abblendlicht einschalten – auch am Tag – und darfst nicht wenden." },
  "328": { t: "Nothalte- und Pannenbucht", e: "Hinweis auf eine Bucht, in der du bei einer Panne oder im Notfall halten kannst." },
  "330.1": { t: "Autobahn", e: "Nur für Kraftfahrzeuge, die bauartbedingt schneller als 60 km/h fahren können. Halten, Wenden und Rückwärtsfahren sind verboten. Die Richtgeschwindigkeit beträgt 130 km/h." },
  "330.2": { t: "Ende der Autobahn", e: "Die Autobahn endet; ab hier gelten wieder die normalen Regeln." },
  "331.1": { t: "Kraftfahrstraße", e: "Ähnlich wie auf der Autobahn: nur für Kraftfahrzeuge, die schneller als 60 km/h fahren können. Halten, Wenden und Rückwärtsfahren sind verboten. Ein- und ausfahren darfst du nur an Kreuzungen und Einmündungen." },
  "331.2": { t: "Ende der Kraftfahrstraße", e: "Die Kraftfahrstraße endet." },
  "332": { t: "Ausfahrt von der Autobahn", e: "Hier beginnt die Ausfahrt. Rechtzeitig blinken und auf dem Ausfädelungsstreifen abbremsen – nicht schon auf der Hauptfahrbahn." },
  "332.1": { t: "Ausfahrttafel außerhalb der Autobahn", e: "Ausfahrt auf einer anderen Straße, z. B. einer autobahnähnlichen Bundesstraße." },
  "333": { t: "Pfeilschild Ausfahrt", e: "Steht am Beginn der Ausfahrt und zeigt die Richtung." },
  "333.1": { t: "Ausfahrt (andere Straßen)", e: "Pfeilschild für die Ausfahrt von Straßen außerhalb der Autobahn." },
  "340": { t: "Leitlinie", e: "Unterbrochene Linie. Du darfst sie überfahren, wenn dadurch niemand gefährdet wird – z. B. zum Überholen." },
  "341": { t: "Wartelinie", e: "Empfiehlt, hier zu warten, wenn du Vorfahrt gewähren musst." },
  "342": { t: "Haifischzähne", e: "Markierung für „Vorfahrt gewähren!“. Die Spitzen zeigen zu dir – du musst warten." },
  "350": { t: "Fußgängerüberweg", e: "Kündigt einen Zebrastreifen an. Fußgängern das Überqueren ermöglichen und nicht überholen." },
  "350.1": { t: "Radschnellweg", e: "Kennzeichnet einen Radschnellweg (seit 2020)." },
  "350.2": { t: "Ende des Radschnellwegs", e: "Der Radschnellweg endet." },
  "353": { t: "Einbahnstraße (Richtzeichen)", e: "Ältere Ausführung: Hinweis auf eine Einbahnstraße. Heute wird Zeichen 220 verwendet." },
  "354": { t: "Wasserschutzgebiet", e: "Hier besonders vorsichtig fahren, wenn du wassergefährdende Stoffe geladen hast (z. B. Öl, Chemikalien)." },
  "356": { t: "Verkehrshelfer", e: "Hier sind Schülerlotsen oder Verkehrshelfer im Einsatz. Ihre Zeichen musst du beachten." },
  "357": { t: "Sackgasse", e: "Die Straße endet, für Fahrzeuge geht es nicht weiter. Das Sinnbild zeigt, ob sie für Fußgänger oder Radfahrende durchlässig ist." },
  "358": { t: "Erste Hilfe", e: "Hinweis auf eine Erste-Hilfe-Stelle." },
  "363": { t: "Polizei", e: "Hinweis auf eine Polizeidienststelle." },
  "365": { t: "Hinweis auf Serviceeinrichtungen", e: "Zeigt Einrichtungen wie Tankstelle, Notrufsäule, Raststätte, Toilette oder Hotel an." },
  "380": { t: "Richtgeschwindigkeit", e: "Empfohlene Höchstgeschwindigkeit. Es ist keine Pflicht – aber bei einem Unfall kann es teurer werden, wenn du schneller warst." },
  "381": { t: "Ende der Richtgeschwindigkeit", e: "Die empfohlene Geschwindigkeit endet." },
  "385": { t: "Ortshinweistafel", e: "Nennt den Namen eines Ortes oder Ortsteils. Achtung: Das ist keine Ortstafel – es beginnt keine geschlossene Ortschaft und es gelten keine innerörtlichen Regeln." },
  "386.1": { t: "Touristischer Hinweis", e: "Weist auf touristische Ziele hin, z. B. Sehenswürdigkeiten." },
  "386.2": { t: "Touristische Route", e: "Weist auf eine touristische Route hin, z. B. eine Ferienstraße." },
  "386.3": { t: "Touristische Unterrichtungstafel", e: "Informiert über eine Region oder Sehenswürdigkeit." },
  "388": { t: "Seitenstreifen für mehrspurige Kfz nicht befahrbar", e: "Der Seitenstreifen ist für Autos und andere mehrspurige Kraftfahrzeuge nicht befahrbar, z. B. weil er nicht befestigt ist." },
  "389": { t: "Seitenstreifen nicht befahrbar", e: "Der Seitenstreifen ist für Fahrzeuge nicht befahrbar." },
  "390": { t: "Mautpflicht", e: "Ab hier ist die Strecke mautpflichtig nach dem Bundesfernstraßenmautgesetz (betrifft vor allem Lkw)." },
  "390.2": { t: "Ende der Mautpflicht", e: "Die Mautpflicht endet." },
  "391": { t: "Mautpflichtige Strecke", e: "Hinweis auf eine Straße, für die Maut zu bezahlen ist." },
  "392": { t: "Zollstelle", e: "Hinweis auf eine Zollstelle." },
  "393": { t: "Informationstafel an Grenzübergängen", e: "Informiert über wichtige Verkehrsregeln im Nachbarland, z. B. die Höchstgeschwindigkeiten." },
  "394": { t: "Laternenring", e: "Kennzeichnet Laternen, die nicht die ganze Nacht brennen. Parkst du dort nachts, musst du dein Fahrzeug selbst beleuchten (z. B. Parkleuchte)." },

  // ---------- Wegweiser & Umleitung ----------
  "405": { t: "Nummernschild für Autobahnen", e: "Nummer der Autobahn." },
  "406": { t: "Nummer des Knotenpunkts", e: "Nummer der Anschlussstelle oder des Autobahnkreuzes – hilft bei der Orientierung und beim Notruf." },
  "410": { t: "Nummernschild für Europastraßen", e: "Nummer der Europastraße." },
  "415": { t: "Wegweiser auf Bundesstraßen", e: "Gelber Wegweiser auf Bundesstraßen." },
  "418": { t: "Wegweiser auf sonstigen Straßen", e: "Weißer Wegweiser auf Straßen mit größerer Verkehrsbedeutung." },
  "419": { t: "Pfeilwegweiser auf sonstigen Straßen", e: "Weißer Pfeilwegweiser auf Straßen mit geringerer Verkehrsbedeutung." },
  "421": { t: "Wegweiser für bestimmte Verkehrsarten", e: "Wegweiser nur für die abgebildete Verkehrsart, z. B. Lkw oder Fahrzeuge mit gefährlichen Gütern." },
  "422": { t: "Wegweiser für bestimmte Verkehrsarten", e: "Wegweiser nur für die abgebildete Verkehrsart, z. B. Lkw über 3,5 t oder Fahrzeuge mit gefährlichen Gütern." },
  "430": { t: "Wegweiser zur Autobahn", e: "Zeigt den Weg zur Autobahn." },
  "432": { t: "Wegweiser zu innerörtlichen Zielen", e: "Zeigt den Weg zu Zielen im Ort, z. B. Bahnhof, Messe oder Krankenhaus." },
  "434": { t: "Tabellenwegweiser", e: "Mehrere Ziele in einer Tabelle, mit Pfeilen für die Richtung." },
  "437": { t: "Straßennamenschild", e: "Nennt den Namen der Straße." },
  "438": { t: "Vorwegweiser", e: "Kündigt die nächste Kreuzung an und zeigt, wohin die Richtungen führen. So kannst du dich rechtzeitig einordnen." },
  "439": { t: "Vorwegweiser", e: "Kündigt die nächste Kreuzung mit ihren Zielen an." },
  "440": { t: "Vorwegweiser zur Autobahn", e: "Kündigt die Zufahrt zur Autobahn an." },
  "441": { t: "Gegliederter Vorwegweiser zur Autobahn", e: "Kündigt die Autobahnzufahrt an und zeigt, in welchen Fahrstreifen du dich für welche Richtung einordnen musst." },
  "442": { t: "Vorwegweiser für bestimmte Verkehrsarten", e: "Vorwegweiser nur für die abgebildete Verkehrsart, z. B. Lkw oder Fahrzeuge mit gefährlichen Gütern." },
  "448": { t: "Ankündigungstafel", e: "Kündigt eine Ausfahrt an – auf Autobahnen meist rund 1000 m vorher." },
  "448.1": { t: "Autohof", e: "Hinweis auf einen Autohof in der Nähe der Ausfahrt (Tanken, Essen, Lkw-Parkplätze)." },
  "449": { t: "Vorwegweiser auf Autobahnen", e: "Kündigt die Ausfahrt mit ihren Zielen an, meist 500 m vorher." },
  "450": { t: "Ankündigungsbake", e: "Baken vor einer Ausfahrt: drei Streifen ca. 300 m, zwei ca. 200 m, einer ca. 100 m vor dem Beginn der Ausfahrt." },
  "453": { t: "Entfernungstafel", e: "Zeigt, wie weit die nächsten Ziele entfernt sind." },
  "454": { t: "Umleitungswegweiser", e: "Zeigt den Weg einer Umleitung." },
  "455.1": { t: "Ankündigung oder Fortsetzung der Umleitung", e: "Zeigt, wie die Umleitung weitergeht: vorher ankündigen, abbiegen oder einordnen." },
  "457.1": { t: "Umleitungsankündigung", e: "Kündigt eine Umleitung an." },
  "457.2": { t: "Ende der Umleitung", e: "Die Umleitung endet." },
  "458": { t: "Planskizze", e: "Zeigt in einer Skizze, wie die Umleitung verläuft." },
  "460": { t: "Bedarfsumleitung", e: "Blaue Umleitungsstrecke mit „U“ und Nummer. Wenn die Autobahn gesperrt ist, folgst du der Nummer der Anschlussstelle, an der du wieder auffahren kannst." },
  "466": { t: "Bedarfsumleitungstafel", e: "Weist auf eine Bedarfsumleitung hin." },
  "467.1": { t: "Umlenkungspfeil", e: "Empfiehlt eine andere Strecke, z. B. bei Stau. Folge dem Symbol bis zum Ende-Zeichen." },
  "467.2": { t: "Ende der Streckenempfehlung", e: "Die empfohlene Ausweichstrecke endet." },

  // ---------- Verkehrslenkungstafeln ----------
  "501": { t: "Überleitungstafel", e: "Die Fahrstreifen werden auf die andere Fahrbahn oder zur Seite übergeleitet, z. B. in einer Autobahnbaustelle. Folge dem gezeigten Verlauf." },
  "505": { t: "Überleitungstafel mit Breitenbeschränkung", e: "Überleitung der Fahrstreifen. Auf dem markierten Fahrstreifen gilt zusätzlich die angegebene Höchstbreite – breitere Fahrzeuge müssen den anderen Fahrstreifen nehmen." },
  "511": { t: "Verschwenkungstafel", e: "Die Fahrstreifen werden seitlich versetzt. Folge ihrem Verlauf und halte deinen Fahrstreifen." },
  "512": { t: "Verschwenkungstafel mit Gegenverkehr", e: "Die Fahrstreifen werden seitlich versetzt, es gibt Gegenverkehr. Rechts halten." },
  "513": { t: "Verschwenkungstafel – kurze Verschwenkung", e: "Kurze seitliche Verschwenkung der Fahrstreifen ohne Gegenverkehr." },
  "514": { t: "Verschwenkungstafel – kurze Verschwenkung mit Gegenverkehr", e: "Kurze seitliche Verschwenkung der Fahrstreifen mit Gegenverkehr." },
  "515": { t: "Verschwenkungstafel mit Breitenbeschränkung", e: "Verschwenkung der Fahrstreifen. Auf dem markierten Fahrstreifen gilt zusätzlich die angegebene Höchstbreite." },
  "521": { t: "Fahrstreifentafel", e: "Zeigt Anzahl und Verlauf der Fahrstreifen." },
  "522": { t: "Fahrstreifentafel mit Gegenverkehr", e: "Zeigt Anzahl und Verlauf der Fahrstreifen in beiden Richtungen." },
  "523": { t: "Fahrstreifentafel mit Tempolimit", e: "Das eingezeichnete Tempolimit gilt nur für den Fahrstreifen, auf dem es abgebildet ist." },
  "524": { t: "Fahrstreifentafel mit Lkw-Verbot", e: "Das eingezeichnete Verbot für Kraftfahrzeuge über 3,5 t gilt nur für den Fahrstreifen, auf dem es abgebildet ist." },
  "525": { t: "Fahrstreifentafel mit Mindestgeschwindigkeit", e: "Die eingezeichnete Mindestgeschwindigkeit gilt nur für den Fahrstreifen, auf dem sie abgebildet ist." },
  "526": { t: "Fahrstreifentafel mit Mindestgeschwindigkeit und Gegenverkehr", e: "Die eingezeichnete Mindestgeschwindigkeit gilt nur für den Fahrstreifen, auf dem sie abgebildet ist." },
  "527": { t: "Fahrstreifentafel mit Gewichtsbeschränkung", e: "Die eingezeichnete Beschränkung der tatsächlichen Masse gilt nur für den Fahrstreifen, auf dem sie abgebildet ist." },
  "528": { t: "Fahrstreifentafel mit Achslastbeschränkung", e: "Die eingezeichnete Beschränkung der Achslast gilt nur für den Fahrstreifen, auf dem sie abgebildet ist." },
  "529": { t: "Fahrstreifentafel mit Höhenbeschränkung", e: "Die eingezeichnete Höhenbeschränkung gilt nur für den Fahrstreifen, auf dem sie abgebildet ist." },
  "531": { t: "Einengungstafel", e: "Ein oder mehrere Fahrstreifen enden. Ordne dich rechtzeitig ein. Bei stockendem Verkehr gilt das Reißverschlussverfahren: bis zum Ende vorfahren und dann abwechselnd einfädeln." },
  "532": { t: "Einengungstafel mit Gegenverkehr", e: "Fahrstreifen enden, es gibt Gegenverkehr. Rechtzeitig einordnen; bei stockendem Verkehr Reißverschluss." },
  "533": { t: "Trennungstafel", e: "Die Fahrstreifen teilen sich auf, z. B. für eine Ausfahrt. Wähle rechtzeitig den richtigen Fahrstreifen." },
  "535": { t: "Einengungstafel mit Tempolimit", e: "Fahrstreifen enden; das eingezeichnete Tempolimit gilt für den gezeigten Fahrstreifen." },
  "536": { t: "Einengungstafel mit Ende der Mindestgeschwindigkeit", e: "Fahrstreifen enden; auf dem gezeigten Fahrstreifen endet die Mindestgeschwindigkeit." },
  "537": { t: "Fahrstreifentafel mit Ende des Tempolimits", e: "Auf dem gezeigten Fahrstreifen endet das Tempolimit." },
  "538": { t: "Fahrstreifentafel mit Ende aller Streckenverbote", e: "Auf dem gezeigten Fahrstreifen enden alle Streckenverbote." },
  "541": { t: "Aufweitungstafel", e: "Ein zusätzlicher Fahrstreifen kommt hinzu." },
  "542": { t: "Aufweitungstafel mit Gegenverkehr", e: "Ein zusätzlicher Fahrstreifen kommt hinzu, es gibt Gegenverkehr." },
  "545": { t: "Aufweitungstafel mit Verkehrszeichen", e: "Ein Fahrstreifen kommt hinzu; das eingezeichnete Zeichen gilt für den gezeigten Fahrstreifen." },
  "546": { t: "Aufweitungstafel mit Mindestgeschwindigkeit", e: "Ein Fahrstreifen kommt hinzu; auf dem gezeigten Fahrstreifen gilt die eingezeichnete Mindestgeschwindigkeit." },
  "550": { t: "Zusammenführungstafel an durchgehender Strecke", e: "Von der Seite kommen weitere Fahrstreifen hinzu, z. B. an einem Autobahnkreuz. Rechne mit einfädelndem Verkehr." },
  "551": { t: "Zusammenführungstafel", e: "Zwei Fahrbahnen werden zusammengeführt. Rechne mit einfädelndem Verkehr." },
  "590": { t: "Blockumfahrung", e: "Zeigt den Umweg um einen Häuserblock, wenn du an der Kreuzung nicht direkt abbiegen darfst." },

  // ---------- Verkehrseinrichtungen ----------
  "600": { t: "Absperrschranke", e: "Sperrt die Straße oder einen Teil davon. Den abgesperrten Bereich darfst du nicht befahren." },
  "605": { t: "Leitbake", e: "Leitet um Hindernisse herum. Die schrägen Streifen zeigen nach unten zu der Seite, auf der du vorbeifahren musst." },
  "610": { t: "Leitkegel", e: "Pylonen grenzen Fahrstreifen ab oder sperren Bereiche. Nicht überfahren." },
  "615": { t: "Fahrbare Absperrtafel", e: "Sperrt einen Fahrstreifen ab, z. B. bei Arbeiten an der Straße. Vorbeifahren auf der freien Seite." },
  "616": { t: "Fahrbare Absperrtafel mit Blinkpfeil", e: "Der Fahrstreifen ist gesperrt. Der Blinkpfeil zeigt, auf welchen Fahrstreifen du wechseln musst." },
  "620": { t: "Leitpfosten", e: "Zeigen den Rand der Straße. Rechts mit schwarzem Streifen, links mit zwei weißen Punkten. Außerorts stehen sie meist 50 m auseinander – gut zum Schätzen von Abstand und Sichtweite." },
  "625": { t: "Richtungstafel in Kurven", e: "Zeigt den Verlauf einer Kurve. Die Spitzen weisen in die Kurvenrichtung." },
  "626": { t: "Leitplatte", e: "Leitet den Verkehr an Hindernissen oder Engstellen vorbei." },
  "627": { t: "Leitmal", e: "Kennzeichnet den Rand der Fahrbahn bei Arbeitsstellen." },
  "628": { t: "Leitschwelle mit Leitbake", e: "Trennt Fahrstreifen in Baustellen. Nicht überfahren." },
  "629": { t: "Leitbord mit Leitbake", e: "Trennt Fahrstreifen in Baustellen. Nicht überfahren." },
  "630": { t: "Parkwarntafel", e: "Rot-weiße Warntafel an Fahrzeugen, die am Fahrbahnrand abgestellt sind (z. B. Anhänger). Die Streifen zeigen, auf welcher Seite du vorbeifahren musst." },

  // ---------- Sonstige ----------
  "720": { t: "Grünpfeil", e: "Du darfst bei Rot rechts abbiegen – aber erst, nachdem du an der Haltlinie angehalten hast. Fußgänger und Radfahrende der freigegebenen Richtung darfst du dabei nicht behindern oder gefährden." },
  "721": { t: "Grünpfeil für den Radverkehr", e: "Nur Radfahrende dürfen bei Rot nach dem Anhalten rechts abbiegen. Für Autos gilt dieser Grünpfeil nicht." },

  // ---------- Zusatzzeichen ----------
  "1000": { t: "Richtungsangaben durch Pfeile", e: "Der Pfeil zeigt, in welche Richtung das Hauptzeichen gilt oder wo die Gefahrstelle liegt." },
  "1001": { t: "Länge einer Strecke", e: "Gibt an, wie lang die Strecke ist, auf der das Zeichen darüber gilt, z. B. „auf 2 km“." },
  "1002": { t: "Verlauf der Vorfahrtstraße", e: "Die dicke Linie zeigt den Verlauf der Vorfahrtstraße. Folgst du der abknickenden Vorfahrt, musst du blinken. Zwischen den Straßen, die an der dünnen Linie liegen, gilt „rechts vor links“." },
  "1004": { t: "Entfernungsangabe", e: "Sagt, wie weit es bis zu der Stelle ist, an der das Zeichen darüber gilt, z. B. „nach 100 m“ oder „Stop in 100 m“." },
  "1005": { t: "Reißverschluss", e: "Kündigt an, ab wo das Reißverschlussverfahren gilt: bis zum Ende des Fahrstreifens vorfahren und dann abwechselnd einfädeln." },
  "1006": { t: "Hinweis auf eine Gefahr", e: "Nennt die Art der Gefahr genauer, z. B. Unfallgefahr oder Staugefahr." },
  "1007": { t: "Hinweis auf eine Gefahr", e: "Nennt die Art der Gefahr genauer, z. B. Ölspur, Rauch, Rollsplitt oder Glatteis." },
  "1008": { t: "Geänderte Verkehrsführung", e: "Weist auf etwas Neues hin, z. B. „Vorfahrt geändert“ oder „Verkehrsführung geändert“. Hier besonders aufmerksam fahren." },
  "1010": { t: "Sinnbilder und Erlaubnisse", e: "Zeigt eine Verkehrsart oder eine Erlaubnis, z. B. „Kinder dürfen auf der Fahrbahn spielen“, „Wintersport erlaubt“ oder ein Fahrzeug-Sinnbild." },
  "1012": { t: "Ergänzende Angaben", e: "Ergänzt das Zeichen darüber, z. B. mit Anfang, Ende, „Ladezone“ oder einem Ort wie „Altenheim“." },
  "1013": { t: "Seitenstreifen", e: "Angaben zur Benutzung des Seitenstreifens." },
  "1014": { t: "Tunnelkategorie", e: "Tunnelkategorie nach ADR: Sie bestimmt, welche gefährlichen Güter durch den Tunnel transportiert werden dürfen." },
  "1020": { t: "Ausnahmen („frei“)", e: "Erlaubt bestimmten Personen oder Fahrzeugen, was das Zeichen darüber verbietet. „Anlieger frei“: Einfahren darf, wer dort wohnt oder dort etwas zu erledigen hat – z. B. einen Besuch oder eine Lieferung." },
  "1022": { t: "Ausnahmen für Zweiräder („frei“)", e: "Erlaubt den abgebildeten Zweirädern, was das Zeichen darüber verbietet, z. B. „Radfahrer frei“." },
  "1024": { t: "Ausnahmen für Kraftfahrzeuge („frei“)", e: "Erlaubt den abgebildeten Fahrzeugen, was das Zeichen darüber verbietet, z. B. „Pkw frei“ oder „Pkw mit Anhänger frei“." },
  "1026": { t: "Ausnahmen („frei“)", e: "Erlaubt bestimmten Fahrzeugen oder Personen, was das Zeichen darüber verbietet, z. B. „Taxi frei“ oder „Linienverkehr frei“." },
  "1028": { t: "Ausnahmen für Baustellen („frei“)", e: "Erlaubt z. B. Baustellenfahrzeugen oder dem Verkehr bis zur Baustelle die Durchfahrt." },
  "1030": { t: "Ausnahme vom Verkehrsverbot", e: "Nimmt bestimmte Fahrzeuge vom Verkehrsverbot bei erhöhter Schadstoffbelastung aus." },
  "1031": { t: "Freistellung Umweltzone", e: "Gibt an, mit welcher Umweltplakette du in die Umweltzone fahren darfst." },
  "1040": { t: "Zeitliche Beschränkung", e: "Das Zeichen darüber gilt nur zu den angegebenen Uhrzeiten." },
  "1042": { t: "Wochentage und Uhrzeiten", e: "Das Zeichen darüber gilt nur an den angegebenen Tagen und zu den angegebenen Zeiten. „Werktags“ heißt Montag bis Samstag." },
  "1044": { t: "Nur mit Parkausweis", e: "Parken nur für die genannten Personen, z. B. Schwerbehinderte mit Parkausweis oder Bewohner mit Bewohnerparkausweis." },
  "1048": { t: "Beschränkung auf eine Verkehrsart („nur“)", e: "Das Zeichen darüber gilt nur für die genannte Verkehrsart, z. B. „nur Sattelkraftfahrzeuge“." },
  "1049": { t: "Beschränkungen und Ausnahmen", e: "Beschränkt das Zeichen darüber auf bestimmte Fahrzeuge oder nimmt Fahrzeuge aus, z. B. „Kraftfahrzeuge bis 25 km/h dürfen überholt werden“." },
  "1050": { t: "Parken für bestimmte Fahrzeuge", e: "Der Platz ist nur für die genannten Fahrzeuge, z. B. Taxis oder Elektrofahrzeuge während des Ladevorgangs." },
  "1052": { t: "Streckenverbot für Gefahrgut", e: "Gefahrgut- oder Wassergefährdungs-Fahrzeuge dürfen die Strecke nicht befahren." },
  "1053": { t: "Regelungen zum Parken", e: "Legt fest, wie geparkt werden darf, z. B. „mit Parkschein“, „gebührenpflichtig“ oder nur in markierten Flächen." },
  "1060": { t: "Sonstige Zusatzzeichen", e: "Weitere Ergänzungen, z. B. „auch Fahrräder und Mofas“ oder „Haltverbot auch auf dem Seitenstreifen“." },
  "2531": { t: "Tollwut – gefährdeter Bezirk", e: "Historisches Zeichen aus der Zeit der Tollwut-Bekämpfung. Heute nicht mehr in Gebrauch." },
  "2532": { t: "Wildtollwut – gefährdeter Bezirk", e: "Historisches Zeichen aus der Zeit der Tollwut-Bekämpfung. Heute nicht mehr in Gebrauch." }
};

// Bilder ohne amtliche Nummer
export const SONDER = {
  "Lichtzeichen": { t: "Lichtzeichen am Bahnübergang", e: "Blinklicht bzw. Ampel am Bahnübergang. Leuchtet erst Gelb und dann Rot, musst du vor dem Andreaskreuz warten." },
  "Nichtamtliches": { t: "Nichtamtliches Hinweisschild", e: "Kein amtliches Verkehrszeichen. Es weist auf Gottesdienste in der Nähe hin." },
  "Hinweiszeichen Wasserschutzgebiet": { t: "Wasserschutzgebiet (Bayern)", e: "Bayerische Ausführung des Hinweises auf ein Wasserschutzgebiet. Fahr besonders vorsichtig, wenn du wassergefährdende Stoffe geladen hast." }
};
